# Generated by Django 4.2.8 on 2023-12-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eightfortypy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Genre', models.CharField(max_length=30)),
                ('Release_Date', models.DateField()),
                ('Album_Image', models.ImageField(blank=True, upload_to='Album_pics')),
            ],
        ),
    ]
